### PR TITLE
Snapshots

### PR DESCRIPTION
**Pull request by smazurov**
- add ability to query snapshots
- add ability to create/copy/attach/detach snapshots
- add tests
- switch to `go mod`

### CODE REVIEW

**Comment by Murray-LIANG** [comment]
Thanks for your contribution. Please add snapshot to `Support Operations` in `README.md`.

**Comment by smazurov** [comment]
@Murray-LIANG done, also added `create` functionality

**Comment by smazurov** [comment]
@Murray-LIANG anything else I can do for you to have this PR merged?

**Comment by Murray-LIANG** [comment]
It looks great. I am merging it.

**Pull request merged**
